// Template generated by reactGen

package main

import (
	"myitcv.io/react"
)

type AppDef struct {
	react.ComponentDef
}

func App() *AppElem {
	return buildAppElem()
}

func (a AppDef) Render() react.Element {
	return react.Div(nil, Login())
}
