// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

type FormWrapElem struct {
	react.Element
}

func buildFormWrap(cd react.ComponentDef) react.Component {
	return FormWrapDef{ComponentDef: cd}
}

func buildFormWrapElem(children ...react.Element) *FormWrapElem {
	return &FormWrapElem{
		Element: react.CreateElement(buildFormWrap, nil, children...),
	}
}

func (f FormWrapDef) RendersElement() react.Element {
	return f.Render()
}
