// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

type InputElem struct {
	react.Element
}

func buildInput(cd react.ComponentDef) react.Component {
	return InputDef{ComponentDef: cd}
}

func buildInputElem(props InputProps, children ...react.Element) *InputElem {
	return &InputElem{
		Element: react.CreateElement(buildInput, props, children...),
	}
}

func (i InputDef) RendersElement() react.Element {
	return i.Render()
}

// IsProps is an auto-generated definition so that InputProps implements
// the myitcv.io/react.Props interface.
func (i InputProps) IsProps() {}

// Props is an auto-generated proxy to the current props of Input
func (i InputDef) Props() InputProps {
	uprops := i.ComponentDef.Props()
	return uprops.(InputProps)
}

func (i InputProps) EqualsIntf(val react.Props) bool {
	return i == val.(InputProps)
}

var _ react.Props = InputProps{}
