// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

type LoginElem struct {
	react.Element
}

func buildLogin(cd react.ComponentDef) react.Component {
	return LoginDef{ComponentDef: cd}
}

func buildLoginElem(children ...react.Element) *LoginElem {
	return &LoginElem{
		Element: react.CreateElement(buildLogin, nil, children...),
	}
}

func (l LoginDef) RendersElement() react.Element {
	return l.Render()
}
